#!/usr/bin/env python3
"""
Inline the written-answer feedback add-on into index.html.

index.html is the single-file deliverable, so the add-on cannot be a separate
<script src>. It is authored in src/feedback-addon.{js,css} for readability and
inlined here between marker comments. Re-running replaces whatever is between
the markers, so this is safe to run repeatedly after editing the source.

    python3 inject-addon.py
"""

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).parent
HTML = ROOT / "index.html"
JS = ROOT / "src" / "feedback-addon.js"
CSS = ROOT / "src" / "feedback-addon.css"

CSS_START = "/* === FEEDBACK ADD-ON CSS (generated by inject-addon.py) === */"
CSS_END = "/* === END FEEDBACK ADD-ON CSS === */"
JS_START = "/* === FEEDBACK ADD-ON JS (generated by inject-addon.py) === */"
JS_END = "/* === END FEEDBACK ADD-ON JS === */"


def main():
    for f in (HTML, JS, CSS):
        if not f.exists():
            sys.exit("missing %s" % f)

    html = HTML.read_text(encoding="utf-8")
    css = CSS.read_text(encoding="utf-8")
    js = JS.read_text(encoding="utf-8")

    css_block = "%s\n%s\n%s" % (CSS_START, css, CSS_END)
    js_block = "%s\n%s\n%s" % (JS_START, js, JS_END)

    # --- CSS: replace between markers, else insert before </style> ---
    if CSS_START in html:
        html = re.sub(
            re.escape(CSS_START) + r".*?" + re.escape(CSS_END),
            lambda m: css_block, html, count=1, flags=re.S,
        )
    else:
        idx = html.index("</style>")
        html = html[:idx] + css_block + "\n" + html[idx:]

    # --- JS: replace between markers, else insert a new script before </body> ---
    if JS_START in html:
        html = re.sub(
            re.escape(JS_START) + r".*?" + re.escape(JS_END),
            lambda m: js_block, html, count=1, flags=re.S,
        )
    else:
        idx = html.rindex("</body>")
        html = html[:idx] + "<script>\n" + js_block + "\n</script>\n\n" + html[idx:]

    HTML.write_text(html, encoding="utf-8")
    kb = len(html.encode("utf-8")) / 1024
    print("injected add-on -> index.html (%.1f KB)" % kb)


if __name__ == "__main__":
    main()
